import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Top Navigation Bar (moved from page.tsx) */}
        <nav className="row-start-1 w-full h-[56px] flex items-center justify-between px-6 sm:px-12 bg-white/80 dark:bg-black/80 shadow-md fixed top-0 left-0 z-50 backdrop-blur border-b border-gray-200 dark:border-gray-800">
          {/* Left: Name/Home Button */}
          <a href="/" className="text-xl font-bold text-gray-900 dark:text-white hover:opacity-80 transition-opacity">Lance Yan</a>
          {/* Right: Nav Links */}
          <div className="flex gap-6 items-center">
            <a href="/" className="flex items-center justify-center w-9 h-9 rounded hover:bg-gray-200 dark:hover:bg-gray-800 transition-colors" aria-label="Home">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
                <path strokeLinecap="round" strokeLinejoin="round" d="M3 12l9-9 9 9M4.5 10.5V21h15V10.5" />
              </svg>
            </a>
            <a href="/projects" className="text-base font-medium text-gray-700 dark:text-gray-200 hover:text-blue-600 dark:hover:text-blue-400 transition-colors">Projects</a>
            <a href="/experience" className="text-base font-medium text-gray-700 dark:text-gray-200 hover:text-blue-600 dark:hover:text-blue-400 transition-colors">Experience</a>
            <a href="/resume" className="text-base font-medium text-gray-700 dark:text-gray-200 hover:text-blue-600 dark:hover:text-blue-400 transition-colors">Resume</a>
          </div>
        </nav>
        <div style={{ paddingTop: 56 }}>{children}</div>
      </body>
    </html>
  );
}
